### ISSUE TITLE
Detect if typing into a text box

### ISSUE THREAD

**Issue by hannes101** [autonome/vimkeybindings#1]
During the transition to Firefox 57 I switched to your plugin, since vimfx is not ported yet. I just found it annoying that even though one is typing text into textboxes the keybindings still work. Don't know if that's fixable, but it really was a pita.

**Comment by autonome** [comment]
Hey! Thanks for reporting it. Fixed and pushed new version to AMO.

**Comment by hannes101** [comment]
Thanks for the really quick fix! Cheers!
