### ISSUE TITLE
Rolling distance is too small on high resolution display

### ISSUE THREAD

**Issue by riocke** [autonome/vimkeybindings#2]
Hi!
I use a vertical 1080 pixel display, which is actually a standard 1080p, And I use the Linux operating system and Firefox browser.
But I don't have development experience, It only advances about 10 actual pixels under a single scroll, This is very hard for webpages that browse a lot of vertical content, How to change it?
Thanks !

**Comment by riocke** [comment]
After a few days, I think it's OK.

**Comment by autonome** [comment]
Might be cool to have it configurable.
